ItemEvents.tooltip(event =>{
//领主灯笼
event.add('born_in_chaos_v1:lord_pumpkinheads_lamp',Text.gold("按住shift显示tetra材料效果"))
event.addAdvanced('born_in_chaos_v1:lord_pumpkinheads_lamp',(Item,addAdvanced,text)=>{
if(event.shift){text.add(Text.red("增加百分之20攻击力，每次攻击使敌人遭受3秒灵魂剥离（效果是造成当前生物生命值17.5%的魔法伤害，还会清除生物的所有状态效果）"))}})
//恶魔灯笼
event.add('born_in_chaos_v1:fel_lamp',Text.gold("按住shift显示tetra材料效果"))
event.addAdvanced('born_in_chaos_v1:fel_lamp',(Item,addAdvanced,text)=>{
if(event.shift){text.add(Text.red("增加2点攻击距离，骑乘时，增加百分之30造成的伤害"))}})
//窃命者头颅
event.add('born_in_chaos_v1:lifestealer_skull',Text.gold("按住shift显示tetra材料效果"))
event.addAdvanced('born_in_chaos_v1:lifestealer_skull',(Item,addAdvanced,text)=>{
if(event.shift){text.add(Text.red("可以铸做京观，血量低于百分之30，获取抗性三"))}})
//梦魇寻踪兽头颅
event.add('born_in_chaos_v1:nightmare_stalker_skull',Text.gold("按住shift显示tetra材料效果"))
event.addAdvanced('born_in_chaos_v1:nightmare_stalker_skull',(Item,addAdvanced,text)=>{
if(event.shift){text.add(Text.red("可以铸做京观，具有隐身buff时，造成的伤害提升百分之30"))}})
//暗金属板
event.add('born_in_chaos_v1:armor_plate_from_dark_metal',Text.gold("按住shift显示tetra材料效果"))
event.addAdvanced('born_in_chaos_v1:armor_plate_from_dark_metal',(Item,addAdvanced,text)=>{
if(event.shift){text.add(Text.red("增加百分之40的攻击力"))}})
//'born_in_chaos_v1:permafrost_shard'
event.add('born_in_chaos_v1:permafrost_shard',Text.gold("按住shift显示tetra材料效果"))
event.addAdvanced('born_in_chaos_v1:permafrost_shard',(Item,addAdvanced,text)=>{
if(event.shift){text.add(Text.red("增加0.5冰霜法强，需要铁魔法模组"))}})
//暴怒符咒
event.add('born_in_chaos_v1:charmof_fury',Text.gold("按住shift显示tetra材料效果"))
event.addAdvanced('born_in_chaos_v1:charmof_fury',(Item,addAdvanced,text)=>{
if(event.shift){text.add(Text.red("每次右键给予玩家中度暴怒buff，并减少50耐久,持续五分钟，已有buff不会触发"))}})
//'born_in_chaos_v1:spider_mandible'
event.add('born_in_chaos_v1:spider_mandible',Text.gold("按住shift显示tetra材料效果"))
event.addAdvanced('born_in_chaos_v1:spider_mandible',(Item,addAdvanced,text)=>{
if(event.shift){text.add(Text.red("使敌人遭受大量debuff"))}})
//'born_in_chaos_v1:dark_atrium'
event.add('born_in_chaos_v1:dark_atrium',Text.gold("按住shift显示tetra材料效果"))
event.addAdvanced('born_in_chaos_v1:dark_atrium',(Item,addAdvanced,text)=>{
if(event.shift){text.add(Text.red("受到致命伤时，免疫此次伤害，并且恢复百分之30生命，cd半小时,同时遭受切割buff（为了限制某个漏洞）"))}})
//窃命者之骨
event.add('born_in_chaos_v1:lifestealer_bone',Text.gold("按住shift显示tetra材料效果"))
event.addAdvanced('born_in_chaos_v1:lifestealer_bone',(Item,addAdvanced,text)=>{
if(event.shift){text.add(Text.red("减少3点攻击力每次攻击给予玩家嗜血之触buff（每次攻击回三血）"))}})
//耐力符咒
event.add('born_in_chaos_v1:charmof_endurance',Text.gold("按住shift显示tetra材料效果"))
event.addAdvanced('born_in_chaos_v1:charmof_endurance',(Item,addAdvanced,text)=>{
if(event.shift){text.add(Text.red("每次右键给予玩家迅捷5buff，并减少50耐久,持续五分钟，已有buff不会触发"))}})
//力量符咒
event.add('born_in_chaos_v1:charmof_power',Text.gold("按住shift显示tetra材料效果"))
event.addAdvanced('born_in_chaos_v1:charmof_power',(Item,addAdvanced,text)=>{
if(event.shift){text.add(Text.red("每次右键给予玩家力量3buff，并减少50耐久,持续五分钟，已有buff不会触发"))}})
//born_in_chaos_v1:stormcallers_horn
event.add('born_in_chaos_v1:stormcallers_horn',Text.gold("按住shift显示tetra材料效果"))
event.addAdvanced('born_in_chaos_v1:stormcallers_horn',(Item,addAdvanced,text)=>{
if(event.shift){text.add(Text.red("增加三点攻击力，每次攻击给自身 sonw_storm buff"))}})
//转变之花
event.add('born_in_chaos_v1:transformative_flower',Text.gold("按住shift显示tetra材料效果"))
event.addAdvanced('born_in_chaos_v1:transformative_flower',(Item,addAdvanced,text)=>{
if(event.shift){text.add(Text.red("攻击伤害从0.8到1.4随机"))}})
//巨食人鱼
event.add('born_in_chaos_v1:sea_terror_eye',Text.gold("按住shift显示tetra材料效果"))
event.addAdvanced('born_in_chaos_v1:sea_terror_eye',(Item,addAdvanced,text)=>{
if(event.shift){text.add(Text.red("给予玩家夜视，水下呼吸，海豚的恩惠"))}})
//隐身符咒
event.add('born_in_chaos_v1:charmof_stealth',Text.gold("按住shift显示tetra材料效果"))
event.addAdvanced('born_in_chaos_v1:charmof_stealth',(Item,addAdvanced,text)=>{
if(event.shift){text.add(Text.red("每次右键给予玩家隐身3buff，并减少50耐久,持续五分钟，已有buff不会触发"))}})
//抗性符咒
event.add('born_in_chaos_v1:charmof_resistance',Text.gold("按住shift显示tetra材料效果"))
event.addAdvanced('born_in_chaos_v1:charmof_resistance',(Item,addAdvanced,text)=>{
if(event.shift){text.add(Text.red("每次右键给予玩家抗性 1 buff，并减少50耐久,持续五分钟，已有buff不会触发"))}})
//暗金属
event.add('born_in_chaos_v1:dark_metal_ingot',Text.gold("按住shift显示tetra材料效果"))
event.addAdvanced('born_in_chaos_v1:dark_metal_ingot',(Item,addAdvanced,text)=>{
if(event.shift){text.add(Text.red("增加百分之20攻击力"))}})
//骇狼首领之牙
event.add('born_in_chaos_v1:fangofthe_hound_leader',Text.gold("按住shift显示tetra材料效果"))
event.addAdvanced('born_in_chaos_v1:fangofthe_hound_leader',(Item,addAdvanced,text)=>{
if(event.shift){text.add(Text.red("使用该材料制作成斧，每次攻击给予玩家极端愤怒buff"))}})
//梦魇寻踪兽爪
event.add('born_in_chaos_v1:nightmare_claw',Text.gold("按住shift显示tetra材料效果"))
event.addAdvanced('born_in_chaos_v1:nightmare_claw',(Item,addAdvanced,text)=>{
if(event.shift){text.add(Text.red("增加7点攻击力，攻击给予玩家加速效果"))}})
//刺壳
event.add('born_in_chaos_v1:spiny_shell',Text.gold("按住shift显示tetra材料效果"))
event.addAdvanced('born_in_chaos_v1:spiny_shell',(Item,addAdvanced,text)=>{
if(event.shift){text.add(Text.red("+3护甲，+1韧性"))}})
//暗影棒
event.add('born_in_chaos_v1:dark_rod',Text.gold("按住shift显示tetra材料效果"))
event.addAdvanced('born_in_chaos_v1:dark_rod',(Item,addAdvanced,text)=>{
if(event.shift){text.add(Text.red("加8完整度"))}})
//骸骨之心
event.add('born_in_chaos_v1:bone_heart',Text.gold("按住shift显示tetra材料效果"))
event.addAdvanced('born_in_chaos_v1:bone_heart',(Item,addAdvanced,text)=>{
if(event.shift){text.add(Text.red("免疫一次伤害，CD十秒"))}})
//焰芒尘
event.add('born_in_chaos_v1:fire_dust',Text.gold("按住shift显示tetra材料效果"))
event.addAdvanced('born_in_chaos_v1:fire_dust',(Item,addAdvanced,text)=>{
if(event.shift){text.add(Text.red("背包含有此物品能进行特殊改造，将焰芒尘涂抹至剑刃，可以赋予武器火焰附加附魔，相应的高温会导致武器耐久减少"))}})
//骨质手柄
event.add('born_in_chaos_v1:bone_handle',Text.gold("按住shift显示tetra材料效果"))
event.addAdvanced('born_in_chaos_v1:bone_handle',(Item,addAdvanced,text)=>{
if(event.shift){text.add(Text.red("加9完整度"))}})
//钻石甲虫碎片
event.add('born_in_chaos_v1:diamond_termite_shard',Text.gold("按住shift显示tetra材料效果"))
event.addAdvanced('born_in_chaos_v1:diamond_termite_shard',(Item,addAdvanced,text)=>{
if(event.shift){text.add(Text.red("耐久相比钻石更低，但是碎片形式的钻石碎片更为锋利，挖掘速度比钻石快，同时+2攻击力"))}})
//招魂球
event.add('born_in_chaos_v1:orbofthe_summoner',Text.gold("按住shift显示tetra材料效果"))
event.addAdvanced('born_in_chaos_v1:orbofthe_summoner',(Item,addAdvanced,text)=>{
if(event.shift){text.add(Text.red("杀死生物给予玩家一个虚魂"))}})
//兽皮
event.add('born_in_chaos_v1:monster_skin',Text.gold("按住shift显示tetra材料效果"))
event.addAdvanced('born_in_chaos_v1:monster_skin',(Item,addAdvanced,text)=>{
if(event.shift){text.add(Text.red("攻击使敌人遭受缓慢buff"))}})
//裂纹头骨
event.add('born_in_chaos_v1:shattered_skull',Text.gold("按住shift显示tetra材料效果"))
event.addAdvanced('born_in_chaos_v1:shattered_skull',(Item,addAdvanced,text)=>{
if(event.shift){text.add(Text.red("可以铸做京观，每次攻击给予玩家力量一"))}})


})
